### ISSUE TITLE
Installation in Google Colab

### ISSUE THREAD

**Issue by Kipkurui-mutai** [maciejkula/glove-python#114]
What is the specific installation in colab? `pip install glove_python` isn't working

**Comment by Kipkurui-mutai** [comment]
Should I edit in the documentation that it is `pip install  glove-python-binary`

**Comment by Kipkurui-mutai** [comment]
I want to contribute to this one.

**Comment by IronFarm** [comment]
@Kipkurui-mutai It would be helpful if could try `pip install glove-python-binary` and let me know if it works.

It should work for python 3.6, 3.7 or 3.8 on Windows or Linux.

**Comment by Kipkurui-mutai** [comment]
It works

**Comment by thochit** [comment]
After install sucess glove-python-binary i can't import glove
