### ISSUE TITLE
single precision

### ISSUE THREAD

**Issue by piskvorky** [maciejkula/glove-python#13]
Current implementation uses double (float64) everywhere.

This is probably an overkill -- single precision (float32) may be enough, and cut the memory down a lot. Both for the C++ and scipy.sparse matrices.

Is there a specific reason behind using double? Are there numerical problems with single?

(word2vec uses single precision everywhere, for example)

**Comment by maciejkula** [comment]
I'll probably make the switch soon.

**Comment by piskvorky** [comment]
Looks like `glove` got its second breath recently -- any particular reason? :)

**Comment by maciejkula** [comment]
I felt bad about abandoning it :(
