### ISSUE TITLE
unable to find Corpus, Glove on OSX

### ISSUE THREAD

**Issue by tcoyze** [maciejkula/glove-python#47]
Macbook Air
El Capitan 10.11.3
Python 2.7.11

Was able to (apparently) successfully install glove-python. However, when attempting to:
`from glove import Corpus, Glove`
I receive the following error:

> Traceback (most recent call last):
>   File "build_glove.py", line 15, in <module>
>     from glove import Glove
>   File "/Users/tyler/gitlab/parsing/quero/venv/lib/python2.7/site-packages/glove/**init**.py", line 1, in <module>
>     from .corpus import Corpus
>   File "/Users/tyler/gitlab/parsing/quero/venv/lib/python2.7/site-packages/glove/corpus.py", line 10, in <module>
>     from .corpus_cython import construct_cooccurrence_matrix
> ImportError: dlopen(/Users/tyler/gitlab/parsing/quero/venv/lib/python2.7/site-packages/glove/corpus_cython.so, 2): no suitable image found.  Did find:
>     /Users/tyler/gitlab/parsing/quero/venv/lib/python2.7/site-packages/glove/corpus_cython.so: mach-o, but wrong architecture

Any thoughts or comments on the matter? I have yet to find a solution.

**Comment by zparcheta** [comment]
Hi, did you find the solution?

**Comment by tcoyze** [comment]
Yes! It had something to do with my gcc environment variables that I was playing around with. It's been such a long time, but I think it was `CPATH` and just removed it.
