### ISSUE TITLE
ImportError: cannot import name Corpus

### ISSUE THREAD

**Issue by igorbpf** [maciejkula/glove-python#54]
When I try to import glove, I get this. Does anyone know a solution?

**Comment by draperunner** [comment]
Use `from glove import Corpus` or `import glove.corpus`

**Comment by igorbpf** [comment]
Weird! Yesterday I did that and it didn't work. After u said, it worked! lol Thanks very much! :-)

**Comment by Palak-B** [comment]
> Use `from glove import Corpus` or `import glove.corpus`

I did the same but I'm getting this.
Cannot import name 'Corpus' from 'glove' (/anaconda3/lib/python3.7/site-packages/glove/__init__.py)

**Comment by lingadhar** [comment]
same error appeared for me as well. Somebody please post the solution if any..Thanks in advance

**Comment by nghidinhit** [comment]
what is the name of python file and package? Is it glove.py?
Change the name of package and python file, it must be different from 'glove'

**Comment by christianfarru** [comment]
Could someone please post the solution (if any)

**Comment by chinmay81192** [comment]
Getting the same error even using a different file name

File "glove_embeddings.py", line 10, in <module>
    from glove import Corpus, Glove
ImportError: cannot import name 'Corpus' from 'glove' (C:\Program Files\Python37\lib\site-packages\glove\__init__.py)

**Comment by bihani-g** [comment]
Try installing the glove package through the following command:
**`! pip install glove_python`**

And then import Corpus and Glove:
**`from glove import Glove, Corpus`**

**Comment by steysie** [comment]
> Try installing the glove package through the following command:
> **`! pip install glove_python`**
> 
> And then import Corpus and Glove:
> **`from glove import Glove, Corpus`**

Unfortunately, still unable to import Corpus. Did anyone find other solutions?

**Comment by bluetyson** [comment]
Not yet.

**Comment by thepratman25** [comment]
I am still getting the same error. Someone please help.

**Comment by gmihran** [comment]
I also had the same problem. The problem was solved when I installed as follows.

pip install glove-python-binary
