### ISSUE TITLE
changes in corpus_cython have no effect

### ISSUE THREAD

**Issue by AutomataVM** [maciejkula/glove-python#58]
hi there, I wanted to modify the corpus_cython.pyx script to take into account the left context of each word.  The problem is, after i run `python setup.py cythonize` and `pip install -e .` those changes have no effect . What might be the cause?

I'm running it on Windows, using Anaconda.
Cheers.

**Comment by AutomataVM** [comment]
solved it. Though i can't get it to analyze the right context and the left one, anything you recommend me to do?

**Comment by maciejkula** [comment]
What do you mean by analyze?

**Comment by AutomataVM** [comment]
Sorry, i was sleepy yesterday, I meant how to check the left context window for each word besides the right context. As in:

"This movie is amazing."

When analyzing the pair (amazing, movie) with amazing as the outer word and movie as the inner one, increment the matrix at the correct position. 

Edit:

**Comment by AutomataVM** [comment]
I managed to re-write the corpus_cython.pyx so it analyzes both left context and right context of each word.

You may close the issue.

**Comment by maciejkula** [comment]
:+1:
